const governorateNameMap = {
    Alexandria: "Alexandria",
    Aswan: "Aswan",
    Asyut: "Asyut",
    Beheira: "Beheira",
    BeniSuef: "Beni Suef",
    Cairo: "Cairo",
    Dakahlia: "Dakahlia",
    Damietta: "Damietta",
    Faiyum: "Faiyum",
    Gharbia: "Gharbia",
    Giza: "Giza",
    Ismailia: "Ismailia",
    KafrElSheikh: "Kafr El Sheikh",
    Luxor: "Luxor",
    Matruh: "Matruh",
    Minya: "Minya",
    Monufia: "Monufia",
    NewValley: "New Valley",
    NorthSinai: "North Sinai",
    PortSaid: "Port Said",
    Qalyubia: "Qalyubia",
    Qena: "Qena",
    RedSea: "Red Sea",
    Sharqia: "Sharqia",
    Sohag: "Sohag",
    SouthSinai: "South Sinai",
    Suez: "Suez",
};
export default governorateNameMap;
